1. Q:      Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException:      No qualifying bean of type edu.sysu.sdcs.web.repository.UserRepo available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}.
   A: Remove "@SpringBootApplication // (exclude={DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class})"  it caused spring no create repo.

2. Q: Caused by: java.lang.NoClassDefFoundError: Lorg/springframework/amqp/core/AmqpTemplate;
   A: Have no idea. I move module provider to web

3. ADD rebbitmq. it can work.